### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by jennmcguire** [phys201/FluorescenceSpectroscopy#16]
Currently you have 4 failing tests: test_data_is_df, test_df_columns, test_df_dim, test_FluoSpecModel_returns_Model. All of these failing tests appear to be from "FileNotFoundError: [Errno 2] No such file or directory: '..\\sim_data\\fluospec_sim_data.csv'"

**Comment by vnmanoharan** [comment]
The issue is that the (relative) path specified in test_io.py is hardcoded.  When `python -m unittest` is run from the root directory of the repo, it tries to look for the file in the wrong place.  Try to use something like what we use in the example package to find the current working directory and base your path on that:
https://github.com/phys201/example/blob/main/example/data_io.py
